# syntax = docker/dockerfile:1.2
FROM node:lts-alpine as build

WORKDIR /app

COPY .yarn/ ./.yarn/
COPY .yarnrc.yml package.json yarn.lock ./ 

COPY lib/utils/package.json ./lib/utils/package.json
COPY services/backend/package.json ./services/backend/package.json

RUN yarn workspaces focus @depop/backend

COPY tsconfig.common.json .
COPY lib/utils ./lib/utils/
COPY services/backend ./services/backend/

WORKDIR /app/services/backend
RUN yarn build

FROM node:lts-alpine as runtime

WORKDIR /app

COPY .yarn/ ./.yarn/
COPY .yarnrc.yml package.json yarn.lock ./ 

ENV NODE_ENV=production

COPY --from=build /app/lib/utils/package.json /app/lib/utils/package.json
COPY --from=build /app/services/backend/package.json /app/services/backend/package.json

RUN yarn workspaces focus @depop/backend

COPY --from=build /app/lib/utils/dist /app/lib/utils/dist
COPY --from=build /app/services/backend/dist /app/services/backend/dist

WORKDIR /app/services/backend

CMD ["yarn", "start:js"]