INSERT INTO "City" ("name")
VALUES ('Almaty'),
    ('Nur-Sultan'),
    ('Shymkent'),
    ('Aktau'),
    ('Aktobe'),
    ('Atyrau'),
    ('Karaganda'),
    ('Kokshetau'),
    ('Kostanai'),
    ('Kizilorda'),
    ('Pavlodar'),
    ('Petropavlsk'),
    ('Rudnyi'),
    ('Semei'),
    ('Taldikorgan'),
    ('Taraz'),
    ('Temirtau'),
    ('Uralsk'),
    ('Ust-kamenogorks'),
    ('Ekibastuz');