BEGIN TRANSACTION;
WITH ins ("title", "order", "sizeGroupTitle") AS (
    VALUES (
            'XS',
            0,
            'womens-wear'
        ),
        (
            'XXS / 32',
            2,
            'womens-wear'
        ),
        (
            'XS / 34',
            4,
            'womens-wear'
        ),
        (
            'S / 36',
            6,
            'womens-wear'
        ),
        (
            'M / 38',
            8,
            'womens-wear'
        ),
        (
            'L / 40',
            10,
            'womens-wear'
        ),
        (
            'XL / 42',
            12,
            'womens-wear'
        ),
        (
            'XXL / 44',
            14,
            'womens-wear'
        ),
        (
            'XXXL / 46',
            16,
            'womens-wear'
        ),
        (
            '4XL / 48',
            18,
            'womens-wear'
        ),
        (
            '5XL / 50',
            20,
            'womens-wear'
        ),
        (
            '6XL / 52',
            22,
            'womens-wear'
        ),
        (
            '7XL / 54',
            24,
            'womens-wear'
        ),
        (
            '8XL / 56',
            26,
            'womens-wear'
        ),
        (
            '9XL / 58',
            28,
            'womens-wear'
        ),
        (
            'One size',
            30,
            'womens-wear'
        ),
        (
            'other',
            32,
            'womens-wear'
        ),
        (
            '35',
            0,
            'womens-shoes'
        ),
        (
            '35.5',
            2,
            'womens-shoes'
        ),
        (
            '36',
            4,
            'womens-shoes'
        ),
        (
            '36.5',
            6,
            'womens-shoes'
        ),
        (
            '37',
            8,
            'womens-shoes'
        ),
        (
            '37.5',
            10,
            'womens-shoes'
        ),
        (
            '38',
            12,
            'womens-shoes'
        ),
        (
            '38.5',
            14,
            'womens-shoes'
        ),
        (
            '39',
            16,
            'womens-shoes'
        ),
        (
            '39.5',
            18,
            'womens-shoes'
        ),
        (
            '40',
            20,
            'womens-shoes'
        ),
        (
            '40.5',
            22,
            'womens-shoes'
        ),
        (
            '41',
            24,
            'womens-shoes'
        ),
        (
            '41.5',
            26,
            'womens-shoes'
        ),
        (
            '42',
            28,
            'womens-shoes'
        ),
        (
            '43',
            30,
            'womens-shoes'
        ),
        (
            '43.5',
            32,
            'womens-shoes'
        ),
        (
            '44',
            34,
            'womens-shoes'
        ),
        (
            'One Size',
            36,
            'womens-shoes'
        ),
        (
            'Other',
            38,
            'womens-shoes'
        ),
        (
            '65A & AA',
            0,
            'bras'
        ),
        (
            '65B',
            2,
            'bras'
        ),
        (
            '65C',
            4,
            'bras'
        ),
        (
            '65D',
            6,
            'bras'
        ),
        (
            '65E',
            8,
            'bras'
        ),
        (
            '65F',
            10,
            'bras'
        ),
        (
            '65G',
            12,
            'bras'
        ),
        (
            '65H',
            14,
            'bras'
        ),
        (
            '65J',
            16,
            'bras'
        ),
        (
            '70A & AA',
            18,
            'bras'
        ),
        (
            '70B',
            20,
            'bras'
        ),
        (
            '70C',
            22,
            'bras'
        ),
        (
            '70D',
            24,
            'bras'
        ),
        (
            '70E',
            26,
            'bras'
        ),
        (
            '70F',
            28,
            'bras'
        ),
        (
            '70G',
            30,
            'bras'
        ),
        (
            '70H',
            32,
            'bras'
        ),
        (
            '70J',
            34,
            'bras'
        ),
        (
            '75A & AA',
            36,
            'bras'
        ),
        (
            '75B',
            38,
            'bras'
        ),
        (
            '75C',
            40,
            'bras'
        ),
        (
            '75D',
            42,
            'bras'
        ),
        (
            '75E',
            44,
            'bras'
        ),
        (
            '75F',
            46,
            'bras'
        ),
        (
            '75G',
            48,
            'bras'
        ),
        (
            '75H',
            50,
            'bras'
        ),
        (
            '75J',
            52,
            'bras'
        ),
        (
            '80A & AA',
            54,
            'bras'
        ),
        (
            '80B',
            56,
            'bras'
        ),
        (
            '80C',
            58,
            'bras'
        ),
        (
            '80D',
            60,
            'bras'
        ),
        (
            '80E',
            62,
            'bras'
        ),
        (
            '80F',
            64,
            'bras'
        ),
        (
            '80G',
            66,
            'bras'
        ),
        (
            '80H',
            68,
            'bras'
        ),
        (
            '80J',
            70,
            'bras'
        ),
        (
            '85A & AA',
            72,
            'bras'
        ),
        (
            '85B',
            74,
            'bras'
        ),
        (
            '85C',
            76,
            'bras'
        ),
        (
            '85D',
            78,
            'bras'
        ),
        (
            '85E',
            80,
            'bras'
        ),
        (
            '85F',
            82,
            'bras'
        ),
        (
            '85G',
            84,
            'bras'
        ),
        (
            '85H',
            86,
            'bras'
        ),
        (
            '85J',
            88,
            'bras'
        ),
        (
            '90A & AA',
            90,
            'bras'
        ),
        (
            '90B',
            92,
            'bras'
        ),
        (
            '90C',
            94,
            'bras'
        ),
        (
            '90D',
            96,
            'bras'
        ),
        (
            '90E',
            98,
            'bras'
        ),
        (
            '90F',
            100,
            'bras'
        ),
        (
            '90G',
            102,
            'bras'
        ),
        (
            '90H',
            104,
            'bras'
        ),
        (
            '90J',
            106,
            'bras'
        ),
        (
            '95A & AA',
            108,
            'bras'
        ),
        (
            '95B',
            110,
            'bras'
        ),
        (
            '95C',
            112,
            'bras'
        ),
        (
            '95D',
            114,
            'bras'
        ),
        (
            '95E',
            116,
            'bras'
        ),
        (
            '95F',
            118,
            'bras'
        ),
        (
            '95G',
            120,
            'bras'
        ),
        (
            '95H',
            122,
            'bras'
        ),
        (
            '95J',
            124,
            'bras'
        ),
        (
            '100A & AA',
            126,
            'bras'
        ),
        (
            '100B',
            128,
            'bras'
        ),
        (
            '100C',
            130,
            'bras'
        ),
        (
            '100D',
            132,
            'bras'
        ),
        (
            '100E',
            132,
            'bras'
        ),
        (
            '100F',
            134,
            'bras'
        ),
        (
            '100G',
            136,
            'bras'
        ),
        (
            '100H',
            138,
            'bras'
        ),
        (
            '100J',
            140,
            'bras'
        ),
        (
            'XS',
            0,
            'mens-wear'
        ),
        (
            'S',
            2,
            'mens-wear'
        ),
        (
            'M',
            4,
            'mens-wear'
        ),
        (
            'L',
            6,
            'mens-wear'
        ),
        (
            'XL',
            8,
            'mens-wear'
        ),
        (
            'XXL',
            10,
            'mens-wear'
        ),
        (
            'XXXL',
            12,
            'mens-wear'
        ),
        (
            '4XL',
            14,
            'mens-wear'
        ),
        (
            '5XL',
            16,
            'mens-wear'
        ),
        (
            '6XL',
            18,
            'mens-wear'
        ),
        (
            '7XL',
            20,
            'mens-wear'
        ),
        (
            '8XL',
            22,
            'mens-wear'
        ),
        (
            '9XL',
            24,
            'mens-wear'
        ),
        (
            '35',
            0,
            'mens-shoes'
        ),
        (
            '35.5',
            2,
            'mens-shoes'
        ),
        (
            '36',
            4,
            'mens-shoes'
        ),
        (
            '36.5',
            6,
            'mens-shoes'
        ),
        (
            '37',
            8,
            'mens-shoes'
        ),
        (
            '37.5',
            10,
            'mens-shoes'
        ),
        (
            '38',
            12,
            'mens-shoes'
        ),
        (
            '38.5',
            14,
            'mens-shoes'
        ),
        (
            '39',
            16,
            'mens-shoes'
        ),
        (
            '39.5',
            18,
            'mens-shoes'
        ),
        (
            '40',
            20,
            'mens-shoes'
        ),
        (
            '40.5',
            22,
            'mens-shoes'
        ),
        (
            '41',
            24,
            'mens-shoes'
        ),
        (
            '41.5',
            26,
            'mens-shoes'
        ),
        (
            '42',
            28,
            'mens-shoes'
        ),
        (
            '43',
            30,
            'mens-shoes'
        ),
        (
            '43.5',
            32,
            'mens-shoes'
        ),
        (
            '44',
            34,
            'mens-shoes'
        ),
        (
            '44.5',
            36,
            'mens-shoes'
        ),
        (
            '45',
            38,
            'mens-shoes'
        ),
        (
            '45.5',
            40,
            'mens-shoes'
        ),
        (
            '46',
            42,
            'mens-shoes'
        ),
        (
            '46.5',
            44,
            'mens-shoes'
        ),
        (
            '47',
            46,
            'mens-shoes'
        ),
        (
            '47.5',
            48,
            'mens-shoes'
        ),
        (
            '48',
            50,
            'mens-shoes'
        ),
        (
            '48.5',
            52,
            'mens-shoes'
        ),
        (
            '49',
            54,
            'mens-shoes'
        ),
        (
            '49.5',
            56,
            'mens-shoes'
        ),
        (
            '50',
            58,
            'mens-shoes'
        ),
        (
            'One Size',
            60,
            'mens-shoes'
        ),
        (
            'Other',
            62,
            'mens-shoes'
        )
)
INSERT INTO "Size" (
        "title",
        "order",
        "sizeGroupId"
    )
SELECT ins."title",
    ins."order",
    sg."id"
FROM "SizeGroup" AS sg
    INNER JOIN ins ON ins."sizeGroupTitle" = sg."title";
COMMIT;